---
- name: copy file in playbook
  hosts: all
  become: yes
    tasks:
      - name: copy app files to server
        copy:
          src: dist/nandini-angular-app/browser/
          dest: /var/www/html/
