apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
     app: pvc-pod
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-volume
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app:  pvc-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
