apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nandini
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      env: prod
  template:
    metadata:
      labels:
        app: nginx
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
